x-base_service: &base_service
  volumes:
    - &store_volume ./store/:/mnt/store
  stdin_open: true
  tty: true
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  rugpt3-xl:
    <<: *base_service
    image: lev145/rugpt3-xl
    build: ./services/ruGPT3XL

  rugpt3:
    <<: *base_service
    image: lev145/rugpt3
    build: ./services/ruGPT3

  download:
    image: lev145/rugpt3-download
    build: ./services/download

    volumes:
      - *store_volume
