x-base_service: &base_service
  volumes:
    - &store_volume ./store/:/mnt/store
  stdin_open: true
  tty: true
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  rugpt-xl:
    <<: *base_service
    image: lev145/rugpt3-xl
    build: ./services/ruGPT3XL
    profiles: ["rugpt-xl"]

  rugpt:
    <<: *base_service
    image: lev145/rugpt3
    build: ./services/ruGPT3
    profiles: ["rugpt"]

  download:
    image: lev145/rugpt3-download
    build: ./services/download
    profiles: ["download"]

    volumes:
      - *store_volume
